### ISSUE TITLE
Not working in latest streamlit version

### ISSUE THREAD

**Issue by gnuille** [teamtv/streamlit_modal#14]
## Environment
Python version: 3.11.6
Streamlit version: 1.28.0
Streamlit-modal version: I have tried both with `main` branch and PyPi versions.

What happens?
Even when using the example code in the README.md:
```
import streamlit as st
from streamlit_modal import Modal

import streamlit.components.v1 as components


modal = Modal(
    "Demo Modal", 
    key="demo-modal",
    
    # Optional
    padding=20,    # default value
    max_width=744  # default value
)
open_modal = st.button("Open")
if open_modal:
    modal.open()

if modal.is_open():
    with modal.container():
        st.write("Text goes here")

        html_string = '''
        <h1>HTML string in RED</h1>

        <script language="javascript">
          document.querySelector("h1").style.color = "red";
        </script>
        '''
        components.html(html_string)

        st.write("Some fancy text")
        value = st.checkbox("Check me")
        st.write(f"Checkbox checked: {value}")
```
The modal does not open and gets stuck in some infinite loop, reaching python recursion limit and breaking.
I don't know if this has to do with the `experimental_rerun` deprecation…
Are you having the same issue?

Thanks.

**Comment by koenvo** [comment]
I merged a fix regarding the `experimental_rerun` a couple of hours ago. Are you sure you tested against the latest main branch?

**Comment by gnuille** [comment]
Yea pretty sure, first I was getting a deprecation warning, then the warning was gone but modals did not work.
Again i think it has to do with last streamlit version 1.28, 1.27 is working fine :O

**Comment by koenvo** [comment]
I just tested it with current main branch, streamlit 1.28 and python 3.10 and it works fine. Do you see any errors?

**Comment by gnuille** [comment]
No, it just enters in an infinite loop of some kind until it reaches recursion limit.
I do not have time to investigate further and with streamlit 1.27 I am fine, if in the future the issue persists I will reopen the issue.
Thanks :)
